### ISSUE TITLE
ECR repository

### ISSUE THREAD

**Issue by denstorti** [devopsacademyau/2020-feb-project1-group1#21]
- create a custom ECR repository for hosting custom wordpress container image
  - you can use official wordpress image but from a custom Dockerfile (i.e. FROM wordpress) - not latest though - please fix a wordpress version
  - make sure to push at least the first version of it to the new ecr

done:
  - I can push new container image tags to an ECR repository
  - I can pull images on ECR from ec2 instances running on my vpc

**Comment by christina-roperto** [comment]
The ECR is done and the makefile is part of issue #31
