### ISSUE TITLE
RDS Solution

### ISSUE THREAD

**Issue by luizfdsilva** [devopsacademyau/2020-feb-project1-group1#5]
- Create terraform for RDS (MySQL)
- Create RDS replicas

## MySQL database
  - create a RDS Aurora MySql database
  - use version `Aurora (MySQL 5.7) 2.07.2`
  - serverless version
    - smallest instance size available if you have issues with serverless
  - no need for aurora replica
  - use same username/password that you setup the systems manager parameters
  - use custom vpc from network stack
    - private subnets
    - security groups with only required permissions for instances on private subnet
  - backup just one day
  - encryption using aws managed key
  - disable performance insights
  - disable enhanced monitoring
  - no need for IAM authentication (wordpress does not support it)
  - disable deletion protection

**Comment by denstorti** [comment]
Consider using Aurora Serverless

**Comment by luizfdsilva** [comment]
> ## MySQL database
> * create a RDS Aurora MySql database
> * use version `Aurora (MySQL 5.7) 2.07.2`
> * serverless version

According with https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-serverless.html#aurora-serverless.limitations 
Aurora Serverless is only available for the following: 
* Aurora with MySQL version 5.6 compatibility

**Comment by denstorti** [comment]
for RDS, based on our requirements SGs need to be created in the VPC as part of the RDS module, not received as input. Can you fix this?

**Comment by luizfdsilva** [comment]
> for RDS, based on our requirements SGs need to be created in the VPC as part of the RDS module, not received as input. Can you fix this?

Done!
